package com.langly.app.notification.entity.enums;

public enum NotificationType {
    PAYMENT_SUCCESS,
    ENROLLMENT_REQUEST,
    ENROLLMENT_APPROVED,
    ENROLLMENT_REJECTED,
    INVOICE_CREATED,
    PAYMENT_RECEIVED,
    INSTALLMENT_REMINDER,
    INSTALLMENT_OVERDUE,
    COURSE_COMPLETED,
    CERTIFICATE_ISSUED,
    SUBSCRIPTION_TRANSFER_DECLARED,
    SUBSCRIPTION_ACTIVATED
}
